version: '3.3'

services:
  db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=problem_manager
    - MYSQL_DATABASE=problem_manager
    - MYSQL_USER=problem_manager
    - MYSQL_PASSWORD=problem_manager
    volumes:
    - mysqlData:/var/lib/mysql

  server:
    build: ./
    entrypoint: bash ./entrypoint.sh
    links:
    - db
    ports:
    - 80:8000

volumes:
  mysqlData:
