# Generated by Django 2.2 on 2019-04-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pid',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
