# Generated by Django 2.2 on 2019-04-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_pid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('oj', 'pid')},
        ),
    ]
