# Generated by Django 2.2 on 2019-04-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20190409_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='origin_link',
            field=models.URLField(default='http://codeforces.com'),
        ),
    ]
