# Generated by Django 2.2 on 2019-04-08 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20190409_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
