# Generated by Django 2.2 on 2019-04-09 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 4, 9, 15, 21, 3, 198367, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.ManyToManyField(related_name='contests', to='problem.Problem')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
