# Generated by Django 2.2 on 2019-04-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20190409_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ac_rate_in_percent',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='accepted_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficult_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='submitted_number',
            field=models.IntegerField(default=-1),
        ),
    ]
