# Generated by Django 2.2 on 2019-09-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20190411_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('problems', models.ManyToManyField(related_name='tags', to='problem.Problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
