# Generated by Django 2.2 on 2019-09-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_tags',
            field=models.TextField(null=True),
        ),
    ]
