# Generated by Django 2.2 on 2019-09-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_problem_problem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
