# Generated by Django 2.2 on 2019-11-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_team_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solved_teams',
            field=models.ManyToManyField(through='problem.Record', to='problem.Team'),
        ),
    ]
