# Generated by Django 2.2 on 2019-11-02 03:42

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_problem_solved_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_mysql.models.JSONField(default=dict)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_problem_prev', to='problem.Problem')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_problem_succ', to='problem.Problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
